flags: {}
extra-package-dbs: []

packages:
- location:
    git: git@github.com:ucsd-progsys/elsa.git
    commit: b418a7b3836877b00c8b3e45dd7ad58f14183a8d

extra-deps:
- elsa-0.2.0.0
- dequeue-0.1.12
- clock-0.7.2

resolver: lts-5.9
